name: ecosystem-packages
description: |
  Registry for scverse ecosystem packages (https://scverse.org/packages/#ecosystem)
project_home: https://github.com/scverse/ecosystem-packages
documentation_home: https://github.com/scverse/ecosystem-packages
install: {}
tags:
  - registry
  - ecosystem
  - infrastructure
license: BSD-3-Clause
version: 1.0.0
authors:
  - scverse
category: core-infrastructure
