name: epiScanpy
description: |
  EpiScanpy is a toolkit to analyse single-cell open chromatin (scATAC-seq) and single-cell
  DNA methylation (for example scBS-seq) data.
project_home: https://github.com/colomemaria/epiScanpy
documentation_home: https://episcanpy.readthedocs.io/en/latest/
tutorials_home: https://episcanpy.readthedocs.io/en/latest/
publications:
  - 10.1038/s41467-021-25131-3
install:
  pypi: episcanpy
tags:
  - scanpy
  - epigenomics
license: BSD-3-Clause
version: v0.3.2
authors:
  - DaneseAnna
  - mrichter23
  - kridsadakorn
  - rLannes
  - le-ander
  - HAL9032
  - michalk8
  - mvinyard
test_command: pip install ".[test]" && pytest
