name: decoupler
description: |
  decoupler is a framework containing different enrichment statistical methods to extract
  biologically driven scores from omics data within a unified framework.
project_home: https://github.com/scverse/decoupler
documentation_home: https://decoupler.readthedocs.io/
inventory: https://decoupler.readthedocs.io/en/latest/
tutorials_home: https://decoupler.readthedocs.io/page/notebooks/
publications:
  - 10.1093/bioadv/vbac016
install:
  pypi: decoupler
  conda: conda-forge::decoupler-py
primary_category: scRNA-seq
tags:
  - functional analysis
license: BSD-3-Clause
language: Python
contact:
  - PauBadiaM
logo: logo.svg
test_command: pip install ".[test]" && pytest
category: core-framework
