name: SpatialData
description: |
  SpatialData is a data framework that comprises a FAIR storage format and a collection of
  python libraries for performant access, alignment, and processing of uni- and multi-modal
  spatial omics datasets.
project_home: https://github.com/scverse/spatialdata
documentation_home: https://spatialdata.scverse.org/
inventory: https://spatialdata.scverse.org/en/stable/
tutorials_home: https://spatialdata.scverse.org/page/tutorials/notebooks/notebooks.html
publications:
  - 10.1038/s41592-024-02212-x
install:
  pypi: spatialdata
primary_category: Data structures
tags:
  - spatial transcriptomics
  - data structures
  - file formats
license: BSD-3-Clause
language: Python
contact:
  - LucaMarconato
  - melonora
logo: logo.svg
category: core-datastructure
