name: scPRINT
description: |
  A single cell foundation model for Gene network inference and more...
project_home: https://github.com/cantinilab/scPRINT
documentation_home: https://cantinilab.github.io/scPRINT/
publications:
  - 10.1101/2024.07.29.605556
install:
  pypi: scprint
primary_category: scRNA-seq
tags:
  - scRNA-seq
  - denoising
  - cell-type annotation
  - gene regulatory networks
  - dimensionality reduction
  - deep learning
  - foundation model
license: MIT
language: Python
version: v1.6.2
contact:
  - jkobject
test_command: pip install . && make test
category: ecosystem
