name: pertpy
description: |
  pertpy is a framework for the analysis of multi-condition omics data.
project_home: https://github.com/scverse/pertpy
documentation_home: https://pertpy.readthedocs.io/en/stable/
tutorials_home: https://pertpy.readthedocs.io/en/stable/tutorials/index.html
install:
  pypi: pertpy
tags:
  - single-cell
  - perturbation
  - condition
license: Apache-2.0
version: v0.7.0
authors:
  - lukas heumos
  - Lilly May
  - Yuge Ji
  - Alejandro Tejada
  - Johannes Köster
  - Emma Dann
  - Xinyue Zhang
  - Xichen Wu
  - Tessa Green
  - Stefan Peidli
  - Antonia Schumacher
  - Gregor Sturm
test_command: |
  pip install ".[dev,test]" && pytest
