name: pegasus
description: |
  Pegasus is a tool for analyzing transcriptomes of millions of single cells.
project_home: https://github.com/lilab-bcb/pegasus
documentation_home: https://pegasus.readthedocs.io/en/stable/
tutorials_home: https://pegasus.readthedocs.io/en/stable/tutorials.html
publications:
  - 10.1038/s41592-020-0905-x
install:
  pypi: pegasuspy
tags:
  - transcriptome analysis
license: BSD-3-Clause
version: v1.7.1
contact:
  - yihming
  - bli25
  - YanayRosen
  - rocherroche
  - jshleap
  - tariqdaouda
  - hoondy
  - joshua-gould
  - slowkow
  - jlchang
test_command: pip install "." && pytest
category: ecosystem
