name: scvelo
description: |
    scVelo is a scalable toolkit for RNA velocity analysis in single cells, based on Bergen et al. [(Nature Biotech, 2020)](https://doi.org/10.1038/s41587-020-0591-3).
project_home: https://github.com/theislab/scvelo
documentation_home: https://scvelo.readthedocs.io
tutorials_home: https://scvelo.readthedocs.io
publications:
    - 10.1038/s41587-020-0591-3
install:
    pypi: scvelo
tags:
    - rna velocity
license: BSD-3-Clause
version: v0.2.5
authors:
    - WeilerP
    - VolkerBergen
test_command: pip install -e '.[dev]' && pytest
