name: CellMapper
description: |
  CellAnnotator is a leightweight tool to transfer labels, expression values and embeddings from reference to query datasets using k-NN mapping. It's fast and versatile, applicable to mapping scenarios in space, across modalities, or from an atlas to a new query dataset.
project_home: https://github.com/quadbio/cell-annotator
documentation_home: https://cell-annotator.readthedocs.io/en/latest/
install:
  pypi: cell-annotator
tags:
  - cell type labels
  - openai
  - large language models
  - automatic annotation
  - cell state
license: MIT
version: v0.1.3
authors:
  - Marius1311
test_command: pip install -e '.[test]' && pytest
