name: ParTIpy
description: |
  Implements Pareto task inference and archetypal analysis for analyzing functional trade-offs in single-cell and spatial omics data.
project_home: https://github.com/saezlab/ParTIpy
documentation_home: https://partipy.readthedocs.io/
tutorials_home: https://partipy.readthedocs.io/
install:
  pypi: partipy
license: MIT
language: Python
primary_category: scRNA-seq
tags:
  - dimensionality reduction
contact:
  - psl-schaefer
  - leotenshii
category: ecosystem
