name: ParTIpy
description: |
  Implements Pareto task inference and archetypal analysis for analyzing functional trade-offs in single-cell and spatial omics data.
project_home: https://github.com/saezlab/ParTIpy
documentation_home: https://partipy.readthedocs.io/en/latest/
tutorials_home: https://partipy.readthedocs.io/en/latest/
install:
  pypi: partipy
license: MIT
tags:
  - "single cell"
  - "archetypal analysis"
  - "division of labor"
  - "representation learning"
version: v0.0.04
authors:
  - psl-schaefer
  - leotenshii
