name: ggml-ot
description: |
  ggml-ot enables supervised optimal transport for classification, clustering and embedding of patient-level single-cell data across conditions, disease states and treatments.
project_home: https://github.com/DaminK/ggml-ot
documentation_home: https://ggml-ot.readthedocs.io/page/
tutorials_home: https://ggml-ot.readthedocs.io/page/tutorials/index.html
publications:
  - 10.48550/arXiv.2506.15383
install:
  pypi: ggml-ot
tags:
  - optimal transport
  - metric learning
  - patient-level
  - sample-level
  - classification
  - clustering
  - embedding
license: MIT
version: v0.9.92
contact:
  - DaminK
logo: logo.png
test_command: |
  pip install poetry && \
  poetry install --with test && \
  poetry run pytest
category: ecosystem
