name: PyDESeq2
description: |
    PyDESeq2 is a python package for bulk RNA-seq differential expression analysis. It is a re-implementation
    from scratch of the main features of the R package DESeq2 (Love et al. 2014).
project_home: https://github.com/owkin/PyDESeq2
documentation_home: https://pydeseq2.readthedocs.io
tutorials_home: https://pydeseq2.readthedocs.io/en/latest/auto_examples/index.html
install:
    pypi: pydeseq2
license: MIT
tags:
    - rna-seq
    - differential-expression
publications:
    - 10.1101/2022.12.14.520412
version: v0.3.0
authors:
    - BorisMuzellec
    - maikia
    - vcabeli
    - mandreux-owkin
test_command: |
    pip install ."[dev]" && pytest
