name: novae
description: |
  Graph-based foundation model for spatial transcriptomics data.
  Zero-shot spatial domain inference, batch-effect correction, and many other features.
project_home: https://github.com/prism-oncology/novae
documentation_home: https://prism-oncology.github.io/novae/
publications:
  - 10.1038/s41592-025-02899-6
install:
  pypi: novae
primary_category: Spatial
tags:
  - spatial transcriptomics
  - deep learning
license: BSD-3-Clause
language: Python
version: v0.2.1
contact:
  - quentinblampey
test_command: pip install ".[dev]" && pytest
category: ecosystem
