name: alphapepttools
description: |
  Read/write functions to and from spatialdata for Deep Visual Proteomics
project_home: https://github.com/MannLabs/dvp-io.git
documentation_home: https://dvp-io.readthedocs.io
tutorials_home: https://dvp-io.readthedocs.io/page/tutorials.html
install:
  pypi: dvp-io
tags:
  - LC/MS-proteomics
  - Spatial Proteomics
  - Reader
license: Apache-2.0
version: 0.4.1
contact:
  - lucas-diedrich
logo: logo.svg
category: ecosystem
