name: pyUCell
description: |
  pyUCell is a package for evaluating gene signatures in single-cell datasets.
  pyUCell signature scores, based on the Mann-Whitney U statistic, are robust
  to dataset size and heterogeneity, and their calculation demands less
  computing time and memory than other available methods, enabling the
  processing of large datasets in a few minutes even on machines with limited
  computing power.
project_home: https://github.com/carmonalab/pyucell
documentation_home: https://pyucell.readthedocs.io/en/latest
tutorials_home: https://pyucell.readthedocs.io/en/latest/notebooks/basic.html
publications:
  - 10.1016/j.csbj.2021.06.043
install:
  pypi: pyucell
tags:
  - single-cell
  - signature scoring
  - module scoring
license: MIT
version: v0.3.0
authors:
  - mass-a
  - sjcarmona
test_command: pip install "." && pytest
