name: SingleRust
description: Production-grade, high-performance toolkit for single-cell RNA sequencing data analysis leveraging Rust's fearless concurrency for scalable pipelines
project_home: https://github.com/SingleRust/SingleRust
documentation_home: https://docs.rs/single_rust
tutorials_home: https://singlerust.com/getting-started
install:
  crates_io: single_rust
publications:
  - 10.1101/2025.08.04.668429
tags:
  - scRNA-seq
  - rust
  - single-cell
  - analysis
license: BSD-3-Clause
version: v0.5.8
contact:
  - ianfd
test_command: cargo test
category: ecosystem
