name: vitessce
description: |
    Vitessce consists of reusable interactive views including a scatterplot, 
    spatial+imaging plot, genome browser tracks, statistical plots, and control 
    views, built on web technologies such as WebGL.
project_home: https://github.com/vitessce/vitessce
documentation_home: https://vitessce.github.io/vitessce-python/
tutorials_home: https://github.com/vitessce/vitessce/tree/main/examples
publications:
    - 10.31219/osf.io/y8thv
install:
    pypi: vitessce
tags:
    - imaging
license: MIT
version: v1.1.20
authors:
    - keller-mark
    - mccalluc
    - ilan-gold
    - thomaslchan
    - manzt
    - john-conroy
    - ngehlenborg
    - jkmarx
    - sehilyi
    - rj3d
    - alexvpickering
    - cosa65
    - dannda
    - alexkb0009
    - ivirshup
    - romanhaa
    - will-moore
test_command: pip install "." && pytest