name: scverse-tutorials
description: |
  Tutorials and tutorials registry for scverse.org/learn.
project_home: https://github.com/scverse/scverse-tutorials
documentation_home: https://scverse-tutorials.readthedocs.io/
tutorials_home: https://scverse-tutorials.readthedocs.io/
tags:
  - tutorials
  - education
  - documentation
license: BSD-3-Clause
contact:
  - grst
  - flying-sheep
category: core-infrastructure
