name: schist
description: schist applies Stochastic Block Models (SBM) to the analysis of single cell data, in particular to identify cell populations
project_home: https://github.com/dawe/schist
documentation_home: https://schist.readthedocs.io
tutorials_home: https://schist.readthedocs.io/page/tutorials.html
install:
  conda: conda-forge::schist
license: BSD-3-Clause
tags:
  - clustering
  - single-cell
publications:
  - 10.1186/s12859-021-04489-7
version: v0.8.1
contact:
  - dawe
  - leomorelli
test_command: |
  pytest conftest.py
category: ecosystem
