name: Cell_BLAST
description: |
  Cell BLAST is a cell querying tool for single-cell transcriptomics data.
project_home: https://github.com/gao-lab/Cell_BLAST
documentation_home: https://cblast.readthedocs.io/en/latest/
publications:
  - 10.1038/s41467-020-17281-7
install:
  pypi: Cell-BLAST
tags:
  - BLAST
license: MIT
version: v0.3.8
contact:
  - Jeff1995
test_command: |
  pip install --upgrade pip flit
  flit install -s
  cd test && python test.py
category: ecosystem
