name: wsidata
description: |
  wsidata is a data-structure for efficient IO of Whole Slide Images based on spatialdata.
project_home: https://github.com/rendeirolab/wsidata
documentation_home: https://wsidata.readthedocs.io/
install:
  pypi: wsidata
primary_category: Data structures
tags:
  - imaging
  - data structures
  - file formats
license: MIT
language: Python
contact:
  - Mr-Milk
  - eabila
  - afrendeiro
test_command: uv run task test
category: ecosystem
