name: Mowgli
description: |
  Paired single-cell multi-omics data integration with Optimal Transport-flavored Nonnegative Matrix Factorization
project_home: https://github.com/cantinilab/mowgli
documentation_home: https://mowgli.readthedocs.io/
publications:
  - 10.1101/2023.02.02.526825
install:
  pypi: mowgli
primary_category: Multimodal
tags:
  - multimodal
  - data integration
  - dimensionality reduction
  - optimal transport
license: GPL-3.0-only
language: Python
contact:
  - gjhuizing
test_command: pip install . && pytest
category: ecosystem
