name: cookiecutter-scverse
description: |
  Cookiecutter template for scverse
project_home: https://github.com/scverse/cookiecutter-scverse
documentation_home: https://cookiecutter-scverse-instance.readthedocs.io/en/latest/
install:
  pypi: cookiecutter-scverse
tags:
  - template
  - cookiecutter
  - project scaffold
  - infrastructure
license: BSD-3-Clause
version: 1.0.0
authors:
  - scverse
category: core-infrastructure
