name: cookiecutter-scverse
description: |
  Cookiecutter template for scverse packages offering automated template sync
project_home: https://github.com/scverse/cookiecutter-scverse
documentation_home: https://cookiecutter-scverse-instance.readthedocs.io/en/latest/template_usage.html
tags:
  - template
  - cookiecutter
license: BSD-3-Clause
version: 0.6.0
contact:
  - grst
  - flying-sheep
category: core-infrastructure
