name: LazySlide
description: |
  LazySlide is a Python library for processing whole slide images (WSI) analysis. It provides a simple interface to perform robust preprocessing and advanced analysis for WSI.
project_home: https://github.com/rendeirolab/lazyslide
documentation_home: https://lazyslide.readthedocs.io/
inventory: https://lazyslide.readthedocs.io/en/stable/
install:
  pypi: lazyslide
primary_category: Imaging
tags:
  - imaging
  - preprocessing
  - segmentation
  - deep learning
license: MIT
language: Python
contact:
  - Mr-Milk
  - eabila
  - afrendeiro
test_command: uv run task test
category: ecosystem
