name: AnnData
description: |
  anndata is a Python package for handling annotated data matrices in memory and on disk,
  positioned between pandas and xarray. anndata offers a broad range of computationally
  efficient features including, among others, sparse data support, lazy operations, and GPU support.
project_home: https://github.com/scverse/anndata
documentation_home: https://anndata.scverse.org/
inventory: https://anndata.scverse.org/en/stable/
tutorials_home: https://anndata.scverse.org/page/tutorials/
publications:
  - 10.21105/joss.04371
install:
  pypi: anndata
  conda: conda-forge::anndata
primary_category: Data structures
tags:
  - data structures
license: BSD-3-Clause
language: Python
contact:
  - flying-sheep
  - ilan-gold
logo: logo.svg
category: core-datastructure
