name: spatial-eggplant
description: |
  Python package designed to transfer information from multiple spatial-transcriptomics data sets to a single reference representing a Common Coordinate Framework (CCF).
project_home: https://github.com/almaan/eggplant
documentation_home: https://spatial-eggplant.readthedocs.io/en/latest/index.html
tutorials_home: https://spatial-eggplant.readthedocs.io/en/latest/index.html
publications:
  - 10.1101/2021.11.11.468178
install:
  pypi: spatial-eggplant
tags:
  - spatial alignment
  - spatial registration
license: MIT
version: v0.2.3
authors:
  - almaan
test_command: pip install "." && pytest
