name: scTriangulate
description: |
  Python package to mix-and-match conflicting clustering results in single cell analysis and generate reconciled clustering solutions
project_home: https://github.com/frankligy/scTriangulate
documentation_home: https://sctriangulate.readthedocs.io/en/latest/get_started.html
tutorials_home: https://sctriangulate.readthedocs.io/en/latest/tutorial.html
publications:
  - 10.1101/2021.10.16.464640
install:
  pypi: sctriangulate
tags:
  - clustering
license: MIT
version: v0.12.0
contact:
  - frankligy
test_command: pip install "." && pytest
