name: moscot
description: |
  moscot is a scalable toolbox for multiomics single-cell optimal transport applications.
project_home: https://github.com/theislab/moscot
documentation_home: https://moscot.readthedocs.io/en/stable/index.html
publications:
  - 10.1101/2023.05.11.540374
install:
  pypi: moscot
tags:
  - optimal transport
  - trajectory inference
  - multi omics
  - spatial
license: BSD-3-Clause
version: v0.4.0
authors:
  - MUCDK
  - giovp
  - michalk8
  - Marius1311
  - zoepiran
test_command: pip install -e '.[dev]' && pytest