name: pychromVAR
description: |
  A python pacakge for chromVAR.
project_home: https://github.com/lzj1769/pychromVAR
documentation_home: https://pychromvar.readthedocs.io/
tutorials_home: https://pychromvar.readthedocs.io/
install:
  pypi: pychromvar
tags:
  - TF
  - scATAC-seq
license: MIT
version: v0.0.3
contact:
  - lzj1769
test_command: |
  test_command: pip install ".[test]" && pytest
category: ecosystem
