name: pychromVAR
description: |
  A python pacakge for chromVAR.
project_home: https://github.com/lzj1769/pychromVAR
documentation_home: https://pychromvar.readthedocs.io/
tutorials_home: https://pychromvar.readthedocs.io/
install:
  pypi: pychromvar
primary_category: Epigenomics
tags:
  - ATAC-seq
  - gene regulatory networks
license: MIT
language: Python
contact:
  - lzj1769
test_command: |
  test_command: pip install ".[test]" && pytest
category: ecosystem
