name: nichepca
description: |
  A Python package for PCA-based spatial domain identification in single-cell spatial transcriptomics data.
project_home: https://github.com/imsb-uke/nichepca
documentation_home: https://nichepca.readthedocs.io/
inventory: https://nichepca.readthedocs.io/en/latest/
tutorials_home: https://nichepca.readthedocs.io/page/notebooks/example.html
install:
  pypi: nichepca
primary_category: Spatial
tags:
  - spatial transcriptomics
  - clustering
license: MIT
language: Python
contact:
  - dschaub95
test_command: |
  uv sync --all-extras && \
  uv run pytest .
category: ecosystem
