name: scCellFie
description: |
  scCellFie infers metabolic activities from single-cell and spatial transcriptomics and offers a variety of downstream analyses.
project_home: https://github.com/earmingol/scCellFie
documentation_home: https://sccellfie.readthedocs.io/
inventory: https://sccellfie.readthedocs.io/en/latest/
tutorials_home: https://sccellfie.readthedocs.io/
install:
  pypi: sccellfie
primary_category: scRNA-seq
tags:
  - spatial transcriptomics
  - functional analysis
  - cell-cell communication
license: MIT
language: Python
contact:
  - earmingol
test_command: |
  python -m pip install --upgrade pip
  python -m pip install -r requirements.txt
  python -m pip install -e .
  pytest -vv --cov --cov-report xml
category: ecosystem
