name: pyLemur
description: |
  Python implementation of the LEMUR algorithm for analyzing multi-condition single-cell RNA-seq data..
project_home: https://github.com/const-ae/pyLemur
documentation_home: https://pyLemur.readthedocs.io/
tutorials_home: https://pylemur.readthedocs.io/page/notebooks/Tutorial.html
publications:
  - 10.1038/s41588-024-01996-0
install:
  pypi: pyLemur
primary_category: scRNA-seq
tags:
  - differential expression
license: MIT
language: Python
contact:
  - const-ae
test_command: pip install -e '.[dev]' && pytest
category: ecosystem
