name: pytximport
description: |
  A Python port of the `tximport` R package for importing transcript-level quantification data from various RNA-seq quantification tools such as `salmon` and `kallisto` and summarizing it to the gene level.
project_home: https://github.com/complextissue/pytximport
documentation_home: https://pytximport.readthedocs.io/
tutorials_home: https://pytximport.readthedocs.io/
install:
  pypi: pytximport
primary_category: bulk RNA-seq
tags:
  - bulk RNA-seq
  - differential expression
  - file formats
license: GPL-3.0-only
language: Python
contact:
  - maltekuehl
test_command: |
  pip install flit poetry && \
  flit install --deps all && \
  coverage run -m pytest
category: ecosystem
