name: pytximport
description: |
  A Python port of the `tximport` R package for importing transcript-level quantification data from various RNA-seq quantification tools such as `salmon` and `kallisto` and summarizing it to the gene level.
project_home: https://github.com/complextissue/pytximport
documentation_home: https://pytximport.readthedocs.io/en/latest/
tutorials_home: https://pytximport.readthedocs.io/en/latest/
install:
  pypi: pytximport
tags:
  - rna-seq
  - bulk-rna-seq
  - differential-expression
license: GPL-3.0-only
version: v0.2.0
authors:
  - maltekuehl
test_command: |
  pip install flit poetry && \
  flit install --deps all && \
  coverage run -m pytest
