name: DoubletDetection
description: |
  DoubletDetection is a Python3 package to detect doublets (technical errors) in single-cell
  RNA-seq count matrices.
project_home: https://github.com/JonathanShor/DoubletDetection
documentation_home: https://doubletdetection.readthedocs.io/en/stable/
tutorials_home: https://doubletdetection.readthedocs.io/en/stable/
publications:
  - 10.1016/j.cels.2019.03.003
install:
  pypi: doubletdetection
tags:
  - doublet
license: MIT
version: v4.2
contact:
  - adamgayoso
  - JonathanShor
  - ambrosejcarr
test_command: pip install ".[test]" && pytest
