name: pcdl
description: physicell data output loader for downstream data analysis in python3.
project_home: https://github.com/elmbeech/physicelldataloader
documentation_home: https://github.com/elmbeech/physicelldataloader/blob/master/README.md
inventory: null
tutorials_home: https://github.com/elmbeech/physicelldataloader/blob/master/man/TUTORIAL_python3_scverse.md
install:
  pypi: pcdl
license: BSD-3-Clause
language: Python
primary_category: Infrastructure
tags:
  - file formats
#publications:
category: ecosystem
contact:
  - ASundus
  - elmbeech
  - engjen
  - furkankurtoglu
  - godzilla-but-nice
  - heberlr
  - johnmetzcar
  - MathCancer
  - rheiland
test_command: pip install . && pytest test/
