name: STMiner
description: |
  Gene-centric spatial transcriptomics for deciphering complex spatial omics data
project_home: https://github.com/xjtu-omics/STMiner
documentation_home: https://stminerdoc.readthedocs.io/en/latest
install:
  pypi: stminer
tags:
  - spatial variable genes
  - spatial patterns
  - optimal transport
  - mechine learning
license: GPL-3.0-or-later
version: v1.1.0
authors:
  - Peisen Sun
test_command: pip install "." && pytest
