name: STMiner
description: |
  Gene-centric spatial transcriptomics for deciphering complex spatial omics data
project_home: https://github.com/xjtu-omics/STMiner
documentation_home: https://stminerdoc.readthedocs.io/
install:
  pypi: stminer
primary_category: Spatial
tags:
  - spatial transcriptomics
  - spatially variable genes
  - deep learning
  - optimal transport
license: GPL-3.0-or-later
language: Python
contact:
  - PSSUN
test_command: pip install "." && pytest
category: ecosystem
