name: bento-tools
description: |
  A Python toolkit for subcellular analysis of spatial transcriptomics data
project_home: https://github.com/ckmah/bento-tools
documentation_home: https://bento-tools.readthedocs.io/
inventory: https://bento-tools.readthedocs.io/en/latest/
tutorials_home: https://bento-tools.readthedocs.io/page/tutorials.html
publications:
  - 10.1186/s13059-024-03217-7
install:
  pypi: bento-tools
primary_category: Spatial
tags:
  - spatial transcriptomics
  - segmentation
license: BSD-2-Clause
language: Python
contact:
  - ckmah
  - noor01
test_command: pip install "." && pytest
category: ecosystem
