name: SnapATAC2
description: |
  SnapATAC2 is the successor of the SnapATAC R package, featuring:
  - Faster and less memory usage, scale to >1M cells.
  - Improved dimension reduction and sampling algorithm.
project_home: https://github.com/kaizhang/SnapATAC2
documentation_home: https://kzhang.org/SnapATAC2/
tutorials_home: https://kzhang.org/SnapATAC2/
publications:
  - 10.1038/s41467-021-21583-9
  - 10.1016/j.cell.2021.10.024
install:
  pypi: snapatac2
tags:
  - SnapATAC
license: MIT
version: v2.1.2
authors:
  - kaizhang
  - yingyuan830
test_command: null
