name: infercnvpy
description: |
  Infer copy number variation (CNV) from scRNA-seq data. Plays nicely with Scanpy.
project_home: https://github.com/icbi-lab/infercnvpy
documentation_home: https://infercnvpy.readthedocs.io/
tutorials_home: https://infercnvpy.readthedocs.io/page/tutorials.html
install:
  pypi: infercnvpy
tags:
  - CNV
license: BSD-3-Clause
version: v0.3.0
contact:
  - grst
test_command: |
  pip install ".[test]" && pytest
category: ecosystem
