name: scanpro
description: robust cell proportion analysis for single cell data
project_home: https://github.com/loosolab/scanpro
documentation_home: https://scanpro.readthedocs.io
tutorials_home: https://scanpro.readthedocs.io/en/latest/proportion_analysis.html
publications:
  - 10.1101/2023.08.14.553234
install:
  pypi: scanpro
tags:
  - single cell
  - proportion analysis
  - multi omics
license: MIT
version: 0.2.0
authors:
  - loosolab
test_command: pip install . && pytest
