name: scverse.github.io
description: |
  scverse.org website
project_home: https://github.com/scverse/scverse.github.io
documentation_home: https://scverse.org
tags:
  - website
  - documentation
license: BSD-3-Clause
authors:
  - gtca
category: core-infrastructure
