name: scverse.github.io
description: |
  scverse.org website
project_home: https://github.com/scverse/scverse.github.io
documentation_home: https://scverse.org
inventory: null
primary_category: Infrastructure
tags:
  - documentation
license: BSD-3-Clause
language: Python
authors:
  - gtca
category: core-infrastructure
