name: PathML
description: |
  An open-source toolkit for computational pathology and machine learning.
project_home: https://pathml.org/
documentation_home: https://pathml.readthedocs.io/
tutorials_home: https://pathml.readthedocs.io/
publications:
  - 10.1158/1541-7786.MCR-21-0665
install:
  pypi: pathml
tags:
  - pathology
license: GPL-2.0-only
version: v2.1.0
contact:
  - jacob-rosenthal
  - ryanccarelli
  - BeeGass
  - MohamedOmar2020
  - Karenxzr
  - ella-dfci
  - surya-narayanan
  - dmbrundage
  - Yu-AnChen
  - jzhang1031
test_command: pip install "." && pytest
category: ecosystem
