name: sopa
description: |
  Technology-invariant pipeline for spatial-omics analysis that
  scales to millions of cells. It includes segmentation, annotation,
  spatial statistics, and efficient visualization.
project_home: https://github.com/gustaveroussy/sopa
documentation_home: https://gustaveroussy.github.io/sopa/
publications:
  - 10.1101/2023.12.22.571863
install:
  pypi: sopa
tags:
  - spatial-omics
  - spatial-transcriptomics
  - multiplex imaging
  - spatialdata
  - pipeline
license: BSD-3-Clause
version: v1.0.0
authors:
  - quentinblampey
test_command: pip install ".[dev,cellpose]" && pytest
