name: integration-testing
description: |
  A repo for integration testing core packages against upstream core packages
project_home: https://github.com/scverse/integration-testing
documentation_home: https://github.com/scverse/integration-testing
tags:
  - testing
  - continuous integration
  - infrastructure
license: MIT
version: 1.0.0
authors:
  - scverse
category: core-infrastructure
