name: governance
description: |
  Governance docs for scverse
project_home: https://github.com/scverse/governance
documentation_home: https://scverse.org/about
inventory: null
primary_category: Infrastructure
tags:
  - documentation
license: BSD-3-Clause
language: Python
contact:
  - Zethson
  - gtca
  - mikelkou
category: core-infrastructure
