name: SCALEX
description: |
  SCALEX is an integration and projection tool for atlas-level single-cell RNA-seq and ATAC-seq data.
project_home: https://github.com/jsxlei/SCALEX
documentation_home: https://scalex.readthedocs.io/
inventory: https://scalex.readthedocs.io/en/latest/
publications:
  - 10.1038/s41467-022-33758-z
install:
  pypi: SCALEX
primary_category: Multimodal
tags:
  - scRNA-seq
  - ATAC-seq
  - data integration
license: MIT
language: Python
contact:
  - jsxlei
test_command: pip install ".[test]" && pytest
category: ecosystem
