name: rapids-singlecell
description: |
  A GPU acclerated python package for singlecell data analysis
project_home: https://github.com/scverse/rapids_singlecell
documentation_home: https://rapids-singlecell.readthedocs.io/en/latest/
tutorials_home: https://rapids-singlecell.readthedocs.io/en/latest/notebooks.html
install:
  pypi: rapids-singlecell
tags:
  - Singlecell Analysis
  - GPU acceleration
  - CUDA
license: MIT
version: v0.7.5
authors:
  - Severin Dicks
test_command: pytest
